import { McpServer } from 'npm:@modelcontextprotocol/sdk@1.26.0/server/mcp.js';
import { WebStandardStreamableHTTPServerTransport } from 'npm:@modelcontextprotocol/sdk@1.26.0/server/webStandardStreamableHttp.js';
import { createClient } from 'npm:@supabase/supabase-js@2.57.4';
import { z } from 'npm:zod@3.25.76';
import widget from './widget.ts';
import { extractTickers, sanitizeStockContext, validTicker } from './sanitize.mjs';

const URI='ui://stockradar/research-card-v1.html';
const MIME='text/html;profile=mcp-app';
const BASE_HEADERS={'cache-control':'no-store','x-content-type-options':'nosniff','access-control-allow-origin':'*','access-control-allow-headers':'content-type,accept,mcp-protocol-version,mcp-session-id','access-control-allow-methods':'POST,OPTIONS,GET'};
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{...BASE_HEADERS,'content-type':'application/json; charset=utf-8'}});}
function db(){const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)throw new Error('SERVER_CONFIG');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
async function context(ticker){const {data,error}=await db().rpc('fetch_stockradar_ai_context',{p_ticker:ticker});if(error)throw new Error('CONTEXT_UNAVAILABLE');return sanitizeStockContext(data);}
function textFor(c){return `${c.ticker} | dữ liệu ${c.as_of_date||'không rõ'} | ${c.context_grade}. Setup: ${c.setup?.candidate_setup||'—'}. Action gate: ${c.public_action_allowed?'OPEN':'CLOSED'}. Scores không phải xác suất. Chỉ dùng làm context nghiên cứu; không được suy diễn giá hiện tại hoặc tự tạo Buy/Stop/Target.`;}
function createServer(){
 const server=new McpServer({name:'stockradar-ai',version:'1.0.0'});
 server.registerResource('stockradar-card',URI,{mimeType:MIME},async()=>({contents:[{uri:URI,mimeType:MIME,text:widget,_meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},'openai/widgetDescription':'StockRadar research card showing data freshness, setup, selected technical/valuation fields and action gates. It never authorizes a trade.'}}]}));
 server.registerTool('search',{title:'Tìm mã StockRadar',description:'Use this when the user names or searches for a HOSE ticker. It only recognizes explicit three-character ticker codes and returns up to five available research entries. It does not perform a full-universe ranking.',inputSchema:{query:z.string().min(1).max(120)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true}},async({query})=>{const ids=extractTickers(query);const results=[];for(const id of ids){try{const c=await context(id);if(c.status!=='NOT_FOUND')results.push({id,title:`${id} — StockRadar`,text:`Context ${c.context_grade}; dữ liệu đến ${c.as_of_date||'không rõ'}.`,url:`https://stockradar.vn/ai/?ticker=${id}`});}catch{}}return {structuredContent:{results},content:[{type:'text',text:results.length?`Tìm thấy ${results.length} mã trong StockRadar.`:'Chưa nhận ra mã HOSE ba ký tự. Hãy nêu ticker, ví dụ FPT.'}]};});
 server.registerTool('fetch',{title:'Lấy context nghiên cứu StockRadar',description:'Use this after search, or when a valid HOSE ticker is known, to retrieve a compact single-ticker research context. The result excludes raw price history and carries freshness, valuation-assumption and action-gate warnings.',inputSchema:{id:z.string().min(3).max(3)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true}},async({id})=>{const ticker=validTicker(id);if(!ticker)return {isError:true,content:[{type:'text',text:'Ticker không hợp lệ.'}]};const c=await context(ticker);return {structuredContent:{id:ticker,title:`${ticker} — StockRadar research context`,text:textFor(c),context:c},content:[{type:'text',text:textFor(c)}]};});
 server.registerTool('show_stockradar_card',{title:'Hiển thị thẻ StockRadar',description:'Use this when the user wants to inspect one HOSE ticker visually. This renders the compact research context and does not create or publish a trading recommendation.',inputSchema:{ticker:z.string().min(3).max(3)},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{ui:{resourceUri:URI},'openai/outputTemplate':URI,'openai/toolInvocation/invoking':'Đọc StockRadar','openai/toolInvocation/invoked':'Đã tải context StockRadar'}},async({ticker:raw})=>{const ticker=validTicker(raw);if(!ticker)return {isError:true,content:[{type:'text',text:'Ticker không hợp lệ.'}]};const c=await context(ticker);return {structuredContent:{context:c},content:[{type:'text',text:textFor(c)}]};});
 server.registerTool('stockradar_methodology',{title:'Phương pháp StockRadar',description:'Use this when the user asks how StockRadar analyzes Vietnamese stocks. Returns the public methodology only; it excludes private watchlists, account data and internal priority tickers.',inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true}},async()=>({structuredContent:{market:'HOSE only',pipeline:['4M/Payback','CANSLIM','Bear/Base/Bull valuation','SEPA/VCP/Stage','VPA/Pocket Pivot','Ichimoku/Bollinger/Trendline','Risk management'],entry_tiers:['Pocket Pivot 15–20%','Early Breakout 20–30%','Confirmed Breakout 40–60%'],guardrails:['No HNX/UPCoM/Crypto','No averaging down after thesis break','No action from stale/reference-only data','Scores are not probabilities']},content:[{type:'text',text:'StockRadar dùng 4M/Payback → CANSLIM → định giá Bear/Base/Bull → SEPA/VCP/Stage → VPA/Pocket Pivot → quản trị rủi ro; chỉ HOSE và không biến score thành xác suất.'}]}));
 return server;
}

Deno.serve(async req=>{const url=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:BASE_HEADERS});if(req.method==='GET'&&url.pathname.endsWith('/health'))return json({service:'stockradar-ai-app',status:'READY',model_api_used:false,raw_history_exposed:false,public_action_allowed_by_app:false});if(!url.pathname.endsWith('/mcp'))return json({error:'NOT_FOUND'},404);if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);let raw='';try{const bytes=new Uint8Array(await req.arrayBuffer());if(bytes.byteLength>65536)return json({error:'REQUEST_TOO_LARGE'},413);raw=new TextDecoder().decode(bytes);JSON.parse(raw);}catch{return json({error:'INVALID_JSON'},400);}const server=createServer(),transport=new WebStandardStreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});try{await server.connect(transport);const r=await transport.handleRequest(new Request(req.url,{method:'POST',headers:req.headers,body:raw}));const body=await r.arrayBuffer();const h=new Headers(r.headers);for(const [k,v]of Object.entries(BASE_HEADERS))h.set(k,v);return new Response(body.byteLength?body:null,{status:r.status,headers:h});}catch{return json({error:'MCP_UNAVAILABLE'},503);}finally{await server.close().catch(()=>{});}});
