import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync('website/assets/project-channel.js','utf8');
class Element{constructor(){this.children=[];this.dataset={};this.textContent='';}append(...x){this.children.push(...x);}setAttribute(){} }
const box={window:{},document:{readyState:'loading',addEventListener(){},createElement:()=>new Element()},URL,Date,console};vm.runInNewContext(source,box);
const {createChannel,questionView}=box.window.StockRadarProjectChannel;
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',Q='33333333-3333-4333-8333-333333333333';
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function setup(){let session={user:{id:A}},reply=async(name,args)=>name==='get_my_stockradar_project_channel'?{data:{available:true}}:{data:{id:Q,status:'WAITING'}},read=async()=>({data:[]}),key=0;const calls=[],states=[],rows=[],filters=[];
 const client={rpc:async(name,args)=>{calls.push({name,args});return reply(name,args);},from(name){const c={select:()=>c,eq:(...a)=>{filters.push(a);return c;},order:()=>c,limit:()=>c,then:res=>read().then(res)};return c;}};
 const api=createChannel({client,getSession:async()=>session,onState:s=>states.push(s),onRows:r=>rows.push(r),uuid:()=>`44444444-4444-4444-8444-${String(++key).padStart(12,'0')}`});return {api,calls,states,rows,filters,setSession(s){session=s;api.bind(s);},setReply(f){reply=f;},setRead(f){read=f;}};
}
test('channel request is an authenticated stored question, not model inference',async()=>{const h=setup();assert.equal(await h.api.connect(),true);const r=await h.api.submit('Phân tích FPT','MEDIUM_TERM');assert.equal(r.id,Q);assert.deepEqual(h.calls.map(c=>c.name),['get_my_stockradar_project_channel','submit_my_stockradar_project_question']);assert.equal(h.calls[1].args.p_question,'Phân tích FPT');assert.ok(!('user_id' in h.calls[1].args));});
test('refresh filters on the current owner and emits received replies',async()=>{const h=setup();await h.api.connect();h.setRead(async()=>({data:[{id:Q,question:'Q',status:'ANSWERED',answer:'From project'}]}));assert.equal(await h.api.refresh(),true);assert.deepEqual(h.filters[0],['user_id',A]);assert.equal(h.rows.at(-1)[0].answer,'From project');});
test('anonymous connection does not read a queue or submit',async()=>{const h=setup();h.setSession(null);assert.equal(await h.api.connect(),false);await assert.rejects(()=>h.api.submit('test'));assert.equal(h.calls.length,0);});
test('unlinked accounts have no Project queue access',async()=>{const h=setup();h.setReply(async()=>({data:{available:false}}));assert.equal(await h.api.connect(),false);await assert.rejects(()=>h.api.submit('test'),/CHANNEL_NOT_LINKED/);});
test('uncertain send retries use the same idempotency key',async()=>{const h=setup();await h.api.connect();let tries=0;h.setReply(async()=>++tries===1?{error:{message:'network'}}:{data:{id:Q,status:'WAITING',duplicate:true}});await assert.rejects(()=>h.api.submit('same text'));await h.api.submit('same text');assert.equal(h.calls[1].args.p_client_key,h.calls[2].args.p_client_key);});
test('a changed question gets a new key after an uncertain request',async()=>{const h=setup();await h.api.connect();h.setReply(async()=>({error:{message:'network'}}));await assert.rejects(()=>h.api.submit('first'));await assert.rejects(()=>h.api.submit('second'));assert.notEqual(h.calls[1].args.p_client_key,h.calls[2].args.p_client_key);});
test('late status and reply loads do not cross accounts',async()=>{const h=setup(),d=deferred();h.setReply(()=>d.promise);const p=h.api.connect();await new Promise(r=>setImmediate(r));h.setSession({user:{id:B}});d.resolve({data:{available:true}});assert.equal(await p,false);assert.equal(h.states.at(-1).available,false);const h2=setup();await h2.api.connect();const d2=deferred();h2.setRead(()=>d2.promise);const p2=h2.api.refresh();await new Promise(r=>setImmediate(r));h2.setSession(null);d2.resolve({data:[{answer:'PRIVATE'}]});assert.equal(await p2,false);assert.equal(h2.rows.at(-1).length,0);});
test('sign out and back in invalidates responses from the old generation',async()=>{const h=setup();await h.api.connect();const d=deferred();h.setRead(()=>d.promise);const p=h.api.refresh();await new Promise(r=>setImmediate(r));h.setSession(null);h.setSession({user:{id:A}});d.resolve({data:[{answer:'PRIVATE'}]});assert.equal(await p,false);});
test('late submit cannot update the new session',async()=>{const h=setup();await h.api.connect();const d=deferred();h.setReply(()=>d.promise);const p=h.api.submit('old account');await new Promise(r=>setImmediate(r));h.setSession({user:{id:B}});d.resolve({data:{id:Q}});assert.equal(await p,null);assert.equal(h.states.at(-1).reset,true);});
test('cancel is a narrow RPC without an owner override',async()=>{const h=setup();await h.api.connect();await h.api.cancel(Q);assert.equal(h.calls[1].name,'cancel_my_stockradar_project_question');assert.equal(h.calls[1].args.p_id,Q);assert.deepEqual(Object.keys(h.calls[1].args),['p_id']);});
test('empty, excessive, invalid-horizon and forged parent input is rejected before RPC',async()=>{const h=setup();await h.api.connect();for(const args of [[''],['x'.repeat(6001)],['x','WRONG'],['x','SHORT_TERM','not-uuid']])await assert.rejects(()=>h.api.submit(...args),/INVALID_QUESTION/);assert.equal(h.calls.length,1);});
test('completed or waiting cards are plain text and cannot inject HTML',()=>{const row={id:Q,status:'ANSWERED',question:'<img src=x>',horizon:'SHORT_TERM',answer_source:'CHATGPT_PROJECT',answer:'<script>bad()</script>'};const e=questionView(row,()=>{},()=>{});assert.ok(e.children.some(n=>n.textContent===row.answer));assert.ok(!source.includes('innerHTML'));assert.ok(!source.includes('api.openai.com'));assert.ok(!source.includes('OPENAI_API_KEY'));assert.match(source,/Chưa có kích hoạt mô hình tự động/);});
test('automatic refresh pauses when hidden and never kicks off inference',()=>{assert.match(source,/document.hidden/);assert.match(source,/pagehide/);assert.match(source,/5000/);assert.ok(!source.includes("operation:'ask'"));});
