import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
class Element{constructor(tag='div'){this.tag=tag;this.children=[];this.dataset={};this.textContent='';}append(...xs){this.children.push(...xs);}replaceChildren(...xs){this.children=[...xs];}setAttribute(){}addEventListener(){} }
const text=e=>e.textContent+' '+e.children.map(text).join(' ');
const A={user:{id:'11111111-1111-4111-8111-111111111111'},access_token:'fixture-a'},B={user:{id:'22222222-2222-4222-8222-222222222222'},access_token:'fixture-b'};
const row={id:'test-report',title:'QA report',body:'PRIVATE_REPORT_A',ticker:'ZZZ',created_at:'2026-09-07T00:00:00Z',data_as_of:null,evidence:[{kind:'cache_snapshot',as_of_date:'2026-09-04',snapshot_id:'synthetic-reference',context_grade:'REFERENCE_ONLY',note:'<img src=x onerror=alert(1)>',secret:'HIDDEN_PRIVATE_FIELD'}]};
function defer(){let resolve;const promise=new Promise(r=>resolve=r);return {resolve,promise};}
function harness(){let session=A,callback,reply=async()=>({data:[row],error:null}),http=async()=>({messages:[{role:'assistant',content:'PRIVATE_HISTORY_A'}]});const target=new Element(),calls=[];
 const client={auth:{getSession:async()=>({data:{session}}),onAuthStateChange:fn=>{callback=fn;}},from:table=>{calls.push({table});const chain={};for(const k of ['select','eq','order','limit'])chain[k]=(...args)=>{calls.push({method:k,args});return chain;};chain.then=(yes,no)=>reply().then(yes,no);return chain;}};
 const box={window:{STOCKRADAR_AUTH_CONFIG:{configured:true,supabaseUrl:'https://fixture.invalid',supabasePublishableKey:'fixture'},StockRadarAuthClient:client},document:{readyState:'loading',baseURI:'https://fixture.invalid/',addEventListener(){},createElement:tag=>new Element(tag),querySelectorAll:()=>[target]},URL,AbortSignal,fetch:async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});const data=await http();return {ok:true,json:async()=>data};}};
 let source=fs.readFileSync('website/assets/chatgpt-workspace.js','utf8');source=source.replace(' window.StockRadarWorkspace=',' window.__qa={showReports,showLegacyHistory,reportView,reportDataLabel,evidenceView,dateOnlyText,timestampText};\n window.StockRadarWorkspace=');vm.runInNewContext(source,box);
 return {api:box.window.__qa,target,calls,setSession(s){session=s;callback?.('SESSION_CHANGED',s);},setReply(fn){reply=fn;},setHttp(fn){http=fn;}};
}
test('date-only observations never inherit the later report timestamp or invented clock',()=>{const h=harness();assert.equal(h.api.reportDataLabel(row),'04/09/2026 (nguồn chỉ xác định ngày)');assert.equal(h.api.reportDataLabel({...row,evidence:[]}),'Chưa xác định — không suy diễn giá hiện tại');assert.equal(h.api.dateOnlyText('2026-02-30'),null);assert.equal(h.api.timestampText('bad'),'Chưa xác định');});
test('evidence and report bodies render as text and never expose unapproved fields',()=>{const h=harness(),el=h.api.reportView(row);assert.match(text(el),/Nguồn và phép kiểm tra/);assert.match(text(el),/synthetic-reference/);assert.match(text(el),/<img src=x/);assert.ok(!text(el).includes('HIDDEN_PRIVATE_FIELD'));const walk=e=>[e,...e.children.flatMap(walk)];assert.ok(!walk(el).some(e=>e.tag==='img'||e.tag==='script'||e.tag==='a'));});
test('unsafe source URLs are not rendered as actionable links or reflected URLs',()=>{const h=harness(),el=h.api.evidenceView([{url:'javascript:alert(1)',kind:'test'},{url:'https://user:password@example.invalid',kind:'test'},{url:'https://example.invalid/source',kind:'test'}]);assert.ok(!text(el).includes('javascript:'));assert.ok(!text(el).includes('password'));assert.match(text(el),/https:\/\/example.invalid\/source/);});
test('owner reports remain owner scoped and do not call any inference endpoint',async()=>{const h=harness();await h.api.showReports(h.target);assert.match(text(h.target),/PRIVATE_REPORT_A/);assert.match(text(h.target),/Đã đọc 1 báo cáo/);assert.ok(h.calls.some(x=>x.method==='eq'&&x.args[0]==='user_id'&&x.args[1]===A.user.id));assert.ok(!h.calls.some(x=>x.url));});
test('logout clears an already displayed report immediately',async()=>{const h=harness();await h.api.showReports(h.target);h.setSession(null);assert.ok(!text(h.target).includes('PRIVATE_REPORT_A'));assert.match(text(h.target),/Phiên đăng nhập đã thay đổi/);});
test('late report cannot appear under another account',async()=>{const h=harness(),d=defer();h.setReply(()=>d.promise);const work=h.api.showReports(h.target);await new Promise(r=>setImmediate(r));h.setSession(B);d.resolve({data:[row],error:null});await work;assert.ok(!text(h.target).includes('PRIVATE_REPORT_A'));});
test('logout and login as the same owner invalidates the earlier-session report request',async()=>{const h=harness(),d=defer();h.setReply(()=>d.promise);const work=h.api.showReports(h.target);await new Promise(r=>setImmediate(r));h.setSession(null);h.setSession(A);d.resolve({data:[row],error:null});await work;assert.ok(!text(h.target).includes('PRIVATE_REPORT_A'));});
test('legacy history is cleared on logout even before reports were opened',async()=>{const h=harness();await h.api.showLegacyHistory(h.target);assert.match(text(h.target),/PRIVATE_HISTORY_A/);h.setSession(null);assert.ok(!text(h.target).includes('PRIVATE_HISTORY_A'));assert.equal(h.calls.find(x=>x.url).body.operation,'history');});
test('late history is rejected across account changes',async()=>{const h=harness(),d=defer();h.setHttp(()=>d.promise);const work=h.api.showLegacyHistory(h.target);await new Promise(r=>setImmediate(r));h.setSession(B);d.resolve({messages:[{role:'assistant',content:'PRIVATE_HISTORY_A'}]});await work;assert.ok(!text(h.target).includes('PRIVATE_HISTORY_A'));});
test('only the most recent refresh can paint reports',async()=>{const h=harness(),d=defer();h.setReply(()=>d.promise);const first=h.api.showReports(h.target);await new Promise(r=>setImmediate(r));h.setReply(async()=>({data:[{...row,body:'LATEST_REPORT'}],error:null}));await h.api.showReports(h.target);d.resolve({data:[row],error:null});await first;assert.match(text(h.target),/LATEST_REPORT/);assert.ok(!text(h.target).includes('PRIVATE_REPORT_A'));});
test('same-account token refresh preserves displayed private reports',async()=>{const h=harness();await h.api.showReports(h.target);h.setSession({...A,access_token:'refreshed-fixture'});assert.match(text(h.target),/PRIVATE_REPORT_A/);});
test('explicit refresh control and no-inference prompt flow remain available',()=>{const source=fs.readFileSync('website/assets/chatgpt-workspace.js','utf8');assert.match(source,/Tải lại báo cáo/);assert.match(source,/showReports\(target\)/);assert.ok(!source.includes('api.openai.com'));assert.ok(!source.includes("operation:'ask'"));});
