import { McpServer } from 'npm:@modelcontextprotocol/sdk@1.26.0/server/mcp.js';
import { WebStandardStreamableHTTPServerTransport } from 'npm:@modelcontextprotocol/sdk@1.26.0/server/webStandardStreamableHttp.js';
import widget from './widget.ts';

const URI='ui://stockradar/native-project-queue-trigger-v2.html';
const MIME='text/html;profile=mcp-app';
const HEADERS={'cache-control':'no-store','x-content-type-options':'nosniff','access-control-allow-origin':'*','access-control-allow-headers':'content-type,accept,mcp-protocol-version,mcp-session-id','access-control-allow-methods':'GET,POST,OPTIONS'};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...HEADERS,'content-type':'application/json; charset=utf-8'}});}
function createServer(){
 const server=new McpServer({name:'stockradar-native-probe',version:'0.2.0'});
 server.registerResource('native-project-queue-trigger',URI,{mimeType:MIME},async()=>({contents:[{uri:URI,mimeType:MIME,text:widget,_meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},'openai/widgetDescription':'Owner-initiated native trigger for the linked StockRadar Project queue. The widget itself reads no database data and calls no separate model API.'}}]}));
 server.registerTool('show_stockradar_native_probe',{title:'Mở nút xử lý hàng đợi StockRadar',description:'Use this when the owner asks to continue or process StockRadar website questions in the current ChatGPT Project. It renders an explicit one-click native trigger. The app itself does not read the website queue, accounts, or chat history and does not call a model API.',inputSchema:{},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{ui:{resourceUri:URI},'openai/outputTemplate':URI,'openai/toolInvocation/invoking':'Mở cầu nối Project','openai/toolInvocation/invoked':'Cầu nối đang chờ người dùng bấm xử lý'}},async()=>({structuredContent:{test:'native_project_queue_trigger',state:'USER_OPT_IN_REQUIRED',native_queue_trigger_ready:true,website_queue_data_read_by_app:false,uses_model_api:false},content:[{type:'text',text:'Đã mở nút xử lý hàng đợi. Chưa có tin nhắn mới được gửi; người dùng cần bấm nút trong widget để tạo đúng một lượt xử lý trong hội thoại hiện tại.'}]}));
 return server;
}
Deno.serve(async req=>{const url=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:HEADERS});if(req.method==='GET'&&url.pathname.endsWith('/health'))return json({service:'stockradar-native-probe',status:'QUEUE_TRIGGER_READY',model_api_used:false,database_access:false,native_queue_trigger_ready:true});if(!url.pathname.endsWith('/mcp'))return json({error:'NOT_FOUND'},404);if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);if(!(req.headers.get('content-type')||'').toLowerCase().startsWith('application/json'))return json({error:'JSON_REQUIRED'},415);let raw='';try{const bytes=new Uint8Array(await req.arrayBuffer());if(bytes.byteLength>16384)return json({error:'REQUEST_TOO_LARGE'},413);raw=new TextDecoder().decode(bytes);JSON.parse(raw);}catch{return json({error:'INVALID_JSON'},400);}const server=createServer(),transport=new WebStandardStreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});try{await server.connect(transport);const r=await transport.handleRequest(new Request(req.url,{method:'POST',headers:req.headers,body:raw}));const body=await r.arrayBuffer();const h=new Headers(r.headers);for(const[k,v]of Object.entries(HEADERS))h.set(k,v);return new Response(body.byteLength?body:null,{status:r.status,headers:h});}catch{return json({error:'MCP_PROBE_UNAVAILABLE'},503);}finally{await server.close().catch(()=>{});}});
