import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=new URL('../supabase/functions/_shared/native-probe/',import.meta.url),html=fs.readFileSync(new URL('widget.html',root),'utf8'),source=html.match(/<script>([\s\S]*?)<\/script>/)[1];
function fixture({native=false,standalone=false}={}){const events={},docEvents={},timers=new Map(),posts=[],nativeCalls=[],els={};let seq=0;for(const id of ['consent','test','cancel','status','preview'])els[id]={checked:false,disabled:true,textContent:'',events:{},addEventListener(n,f){this.events[n]=f;}};const parent={postMessage(m){posts.push(m);}};const window={parent,addEventListener(n,f){events[n]=f;}};if(standalone)window.parent=window;if(native)window.openai={sendFollowUpMessage:async p=>{nativeCalls.push(p);}};const document={hidden:false,getElementById:id=>els[id],addEventListener(n,f){docEvents[n]=f;}};const box={window,document,crypto:{getRandomValues:x=>{x.fill(7);}},Uint8Array,Map,setTimeout:(f,delay)=>{const id=++seq;timers.set(id,{f,delay});return id;},clearTimeout:id=>timers.delete(id)};vm.runInNewContext(source,box);return {els,posts,nativeCalls,document,events,docEvents,reply(m,result={},error=null,from=parent){events.message({source:from,data:{jsonrpc:'2.0',id:m.id,...(error?{error}:{result})}});},async flush(){await new Promise(r=>setImmediate(r));},async time(delay){for(const [id,t]of [...timers])if(t.delay===delay){timers.delete(id);t.f();}await new Promise(r=>setImmediate(r));},arm(){els.consent.checked=true;els.consent.events.change();els.test.events.click();}};}
async function ready(opts={}){const h=fixture(opts);h.reply(h.posts[0],{hostCapabilities:{}});await h.flush();return h;}
test('render only initializes UI and has no private data or model endpoint calls',async()=>{const h=await ready();assert.equal(h.posts.filter(x=>x.method==='ui/message').length,0);for(const text of ['fetch(','localStorage','SUPABASE_SERVICE_ROLE_KEY','api.openai.com'])assert.ok(!source.includes(text));});
test('consent alone sends nothing; explicit click produces one delayed bounded message',async()=>{const h=await ready();h.els.consent.checked=true;h.els.consent.events.change();await h.time(3000);assert.equal(h.posts.filter(x=>x.method==='ui/message').length,0);h.els.test.events.click();await h.time(3000);const messages=h.posts.filter(x=>x.method==='ui/message');assert.equal(messages.length,1);assert.match(messages[0].params.content[0].text,/SR-NATIVE-/);h.reply(messages[0]);await h.flush();h.els.test.events.click();await h.time(3000);assert.equal(h.posts.filter(x=>x.method==='ui/message').length,1);assert.match(h.els.status.textContent,/Chưa tự xác nhận/);});
test('cancel and uncheck stop a pending send',async()=>{for(const mode of ['cancel','uncheck']){const h=await ready();h.arm();if(mode==='cancel')h.els.cancel.events.click();else{h.els.consent.checked=false;h.els.consent.events.change();}await h.time(3000);assert.equal(h.posts.filter(x=>x.method==='ui/message').length,0);}});
test('hidden or unloaded probe cannot send delayed messages',async()=>{for(const mode of ['hidden','pagehide']){const h=await ready();h.arm();if(mode==='hidden'){h.document.hidden=true;h.docEvents.visibilitychange();}else h.events.pagehide();await h.time(3000);assert.equal(h.posts.filter(x=>x.method==='ui/message').length,0);}});
test('forged non-parent response cannot initialize the host',async()=>{const h=fixture();h.reply(h.posts[0],{},null,{});await h.flush();h.arm();await h.time(3000);assert.equal(h.posts.filter(x=>x.method==='ui/message').length,0);});
test('native alias is only used after explicit method-not-found',async()=>{const h=await ready({native:true});h.arm();await h.time(3000);h.reply(h.posts.find(x=>x.method==='ui/message'),{}, {code:-32601});await h.flush();assert.equal(h.nativeCalls.length,1);});
test('ambiguous timeout never retries or falls back to another send',async()=>{const h=await ready({native:true});h.arm();await h.time(3000);await h.time(7000);assert.equal(h.nativeCalls.length,0);assert.match(h.els.status.textContent,/Không gửi lại/);h.els.test.events.click();await h.time(3000);assert.equal(h.posts.filter(x=>x.method==='ui/message').length,1);});
test('legacy native bridge may be used when standard initialization is unavailable',async()=>{const h=fixture({native:true});await h.time(7000);h.arm();await h.time(3000);assert.equal(h.nativeCalls.length,1);});
test('standalone web page is not a native ChatGPT host',async()=>{const h=fixture({native:true,standalone:true});h.arm();await h.time(3000);assert.equal(h.nativeCalls.length,0);assert.equal(h.posts.length,0);});
test('host rejection cannot claim success or use a paid fallback',async()=>{const h=await ready({native:true});h.arm();await h.time(3000);h.reply(h.posts.find(x=>x.method==='ui/message'),{}, {code:-32000});await h.flush();assert.match(h.els.status.textContent,/chưa chấp nhận/);assert.equal(h.nativeCalls.length,0);});
test('server exposes only static probe resource and does not read environment/database',()=>{const s=fs.readFileSync(new URL('index.ts',root),'utf8');for(const x of ['Deno.env','createClient','read_stockradar_project_inbox','OPENAI_API_KEY','fetch('])assert.ok(!s.includes(x),x);assert.match(s,/new McpServer/);assert.match(s,/8192/);assert.match(s,/native_model_reply_verified:false/);});
