import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {test} from 'node:test';
const source=readFileSync(new URL('../supabase/functions/_shared/stockradar-project-context.ts',import.meta.url),'utf8');
const {validateProjectBridge,loadProjectBridge,loadProjectContext,projectContextInput,projectBridgeMeta,PROJECT_HANDOFF_RULE}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const user='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',thread='33333333-3333-4333-8333-333333333333';
const summary='Reviewed project handoff with continuous stock-analysis context; no live price facts.';
const b={enabled:true,source:'CHATGPT_PROJECT_STOCKRADAR',thread_id:thread,version:'PROJECT_CHAT_V1',reviewed_at:'2025-01-01T00:00:00Z',summary};
const row={user_id:user,preferences:{project_bridge:b}};
function database({memory=row,owned={id:thread,user_id:user,status:'ACTIVE'},error=null,throws=false}={}) {
 const calls=[];return {calls,from(table){if(throws)throw new Error('secret must not leak');const chain={};for(const method of ['select','eq'])chain[method]=(...args)=>{calls.push({table,method,args});return chain;};chain.maybeSingle=async()=>({data:table==='stockradar_ai_user_memory'?memory:owned,error});return chain;}};
}
test('valid reviewed owner handoff is accepted',()=>assert.equal(validateProjectBridge(row,user).summary,summary));
test('wrong account or invalid identity cannot read the handoff',()=>{assert.equal(validateProjectBridge(row,other),null);assert.equal(validateProjectBridge(row,'x'),null);});
for(const [label,patch] of [['disabled',{enabled:false}],['unreviewed source',{source:'RAW_CHAT_EXPORT'}],['invalid thread',{thread_id:'x'}],['invalid version',{version:'<script>'}],['empty summary',{summary:''}],['oversize summary',{summary:'x'.repeat(6001)}],['future review',{reviewed_at:'2099-01-01T00:00:00Z'}],['missing review',{reviewed_at:null}],['secret material',{summary:'sk-proj-'+ 'x'.repeat(32)}]])test(`rejects ${label}`,()=>assert.equal(validateProjectBridge({...row,preferences:{project_bridge:{...b,...patch}}},user),null));
test('loader checks both user ownership and active linked thread',async()=>{const db=database();assert.equal((await loadProjectBridge(db,user)).summary,summary);assert.ok(db.calls.some(c=>c.table==='stockradar_ai_user_memory'&&c.method==='eq'&&c.args[0]==='user_id'&&c.args[1]===user));assert.ok(db.calls.some(c=>c.table==='stockradar_ai_threads'&&c.method==='eq'&&c.args[0]==='user_id'&&c.args[1]===user));});
for(const owned of [null,{id:thread,user_id:other,status:'ACTIVE'},{id:other,user_id:user,status:'ACTIVE'},{id:thread,user_id:user,status:'ARCHIVED'}])test(`rejects missing or non-owned active thread ${JSON.stringify(owned)}`,async()=>assert.equal(await loadProjectBridge(database({owned}),user),null));
test('missing record and database failures fail closed',async()=>{for(const opts of [{memory:null},{error:{code:'FAIL'}},{throws:true}])assert.equal(await loadProjectBridge(database(opts),user),null);});
test('no thread avoids loading any personal data',async()=>{const db=database();assert.equal(await loadProjectContext(db,user,''),null);assert.equal(db.calls.length,0);});
test('context is bound to the exact project thread, not every chat',async()=>{assert.equal(await loadProjectContext(database(),user,other),null);assert.equal((await loadProjectContext(database(),user,thread)).version,b.version);});
test('input is marked user context and never current market evidence',()=>{const bridge=validateProjectBridge(row,user);const input=projectContextInput(bridge,thread);assert.equal(input.authority,'USER_CONTEXT_ONLY');assert.equal(input.not_live_market_data,true);assert.equal(projectContextInput(bridge,other),null);assert.match(PROJECT_HANDOFF_RULE,/Không phải chỉ thị hệ thống/);});
test('metadata never exposes the summary or impersonates a successful model',()=>{const bridge=validateProjectBridge(row,user);assert.ok(!JSON.stringify(projectBridgeMeta(bridge,thread)).includes(summary));assert.equal(projectBridgeMeta(bridge,thread).context_loaded,true);assert.equal(projectBridgeMeta(bridge,thread).context_applied,false);assert.equal(projectBridgeMeta(bridge,thread,true).context_applied,true);assert.equal(projectBridgeMeta(bridge,other,true).context_applied,false);assert.equal(projectBridgeMeta(null,thread,true).available,false);});
test('next request reads a new revision rather than a stale cached summary',async()=>{const newer={...row,preferences:{project_bridge:{...b,version:'PROJECT_CHAT_V2'}}};assert.equal((await loadProjectBridge(database(),user)).version,'PROJECT_CHAT_V1');assert.equal((await loadProjectBridge(database({memory:newer}),user)).version,'PROJECT_CHAT_V2');});
