import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";
import { STOCKRADAR_SYSTEM_CORE, deterministicStockRadarAnswer, normalizeResearchContext, stockRadarMode } from "../_shared/stockradar-core.ts";

const ORIGINS=new Set(["https://stockradar.vn","https://www.stockradar.vn","https://nguyenlinhns-arch.github.io","http://localhost:8000","http://127.0.0.1:8000"]);
const HORIZONS=new Set(["SHORT_TERM","MEDIUM_TERM","LONG_TERM","ACCUMULATION"]),TIERS=new Set(["FREE","TRIAL","PAID"]);
let providerDisabledUntil=0;
function cors(origin){const h={Vary:"Origin","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"};if(origin&&ORIGINS.has(origin))Object.assign(h,{"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"});return h}
function json(body,status,origin,extra={}){return new Response(JSON.stringify(body),{status,headers:{...cors(origin),...extra,"Content-Type":"application/json; charset=utf-8"}})}
function validTicker(v){return/^[A-Z0-9]{3}$/.test(v)&&/[A-Z]/.test(v)}
function clean(v,max=700){return String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,max)}
function openAIText(p){if(typeof p?.output_text==='string'&&p.output_text.trim())return p.output_text.trim();const a=[];for(const i of Array.isArray(p?.output)?p.output:[])for(const c of Array.isArray(i?.content)?i.content:[])if(c?.type==='output_text'&&typeof c.text==='string')a.push(c.text);return a.join('\n').trim()}
function appendPosition(answer,scope,ticker,watch){if(scope!=='ticker')return answer;const item=watch.find(r=>r.ticker===ticker&&r.owns_stock);if(!item)return answer;const bits=[];if(item.cost_basis!=null)bits.push(`giá vốn tự khai báo ${Number(item.cost_basis).toLocaleString('vi-VN')}đ`);if(item.portfolio_weight_pct!=null)bits.push(`tỷ trọng ${Number(item.portfolio_weight_pct).toLocaleString('vi-VN',{maximumFractionDigits:1})}%`);return bits.length?`${answer}\n\nVỊ THẾ CỦA BẠN: ${bits.join(' · ')}.`:answer}

Deno.serve(async req=>{
  const origin=req.headers.get('origin');if(origin&&!ORIGINS.has(origin))return json({status:'FORBIDDEN_ORIGIN'},403,null);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(req.method!=='POST')return json({status:'METHOD_NOT_ALLOWED'},405,origin);
  const authorization=req.headers.get('authorization')||'',token=authorization.toLowerCase().startsWith('bearer ')?authorization.slice(7).trim():'';if(!token)return json({status:'UNAUTHORIZED'},401,origin);
  const url=Deno.env.get('SUPABASE_URL')||'',anon=Deno.env.get('SUPABASE_ANON_KEY')||'',serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!anon||!serviceKey)return json({status:'SERVICE_UNAVAILABLE'},503,origin);
  const auth=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false}}),db=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}),{data:userData,error:userError}=await auth.auth.getUser(token),user=userData?.user;if(userError||!user)return json({status:'UNAUTHORIZED'},401,origin);
  let body;try{body=await req.json()}catch{return json({status:'INVALID_REQUEST',reason:'INVALID_JSON'},400,origin)}
  const ticker=String(body.ticker||'').trim().toUpperCase(),scopeRaw=String(body.scope||'auto').trim().toLowerCase(),horizon=String(body.horizon||'SHORT_TERM').trim().toUpperCase(),message=clean(body.message);if(!HORIZONS.has(horizon)||!message||!['auto','ticker','portfolio'].includes(scopeRaw))return json({status:'INVALID_REQUEST'},400,origin);const scope=scopeRaw==='portfolio'?'portfolio':ticker?'ticker':'portfolio';if(scope==='ticker'&&!validTicker(ticker))return json({status:'INVALID_REQUEST',reason:'INVALID_TICKER'},400,origin);
  const [{data:profile,error:profileError},{data:watchRows}]=await Promise.all([db.from('profiles').select('account_tier,account_status').eq('id',user.id).maybeSingle(),db.from('watchlist_items').select('ticker,horizon,owns_stock,alert_enabled,cost_basis,portfolio_weight_pct,created_at').eq('user_id',user.id).is('removed_at',null).order('owns_stock',{ascending:false}).order('created_at',{ascending:true}).limit(20)]);
  const tier=String(profile?.account_tier||'').toUpperCase();if(profileError||String(profile?.account_status||'').toUpperCase()!=='ACTIVE'||!TIERS.has(tier))return json({status:'FORBIDDEN',reason:'ACCOUNT_INACTIVE'},403,origin);
  const watch=(Array.isArray(watchRows)?watchRows:[]).flatMap(row=>{const wt=String(row.ticker||'').trim().toUpperCase();if(!validTicker(wt))return[];return[{ticker:wt,horizon:String(row.horizon||'SHORT_TERM'),owns_stock:row.owns_stock===true,alert_enabled:row.alert_enabled===true,cost_basis:row.cost_basis==null?null:Number(row.cost_basis),portfolio_weight_pct:row.portfolio_weight_pct==null?null:Number(row.portfolio_weight_pct)}]});
  if(scope==='portfolio'&&!watch.length)return json({status:'NO_WATCHLIST',scope,tier,answer:'VIỆC CẦN LÀM TRƯỚC: tài khoản chưa có mã trong watchlist. Hãy thêm mã để StockRadar AI phân tích danh mục.',quota_consumed:false},200,origin);
  const requestedTickers=scope==='ticker'?[ticker]:[...new Set(watch.map(x=>x.ticker))];
  const contexts=(await Promise.all(requestedTickers.map(async item=>{const{data,error}=await db.rpc('fetch_stockradar_ai_context',{p_ticker:item});return error?null:normalizeResearchContext(data)}))).filter(Boolean);
  const hasReady=contexts.some(c=>c.context_grade==='RESEARCH_READY'),hasReference=contexts.length>0,mode=stockRadarMode(false,hasReady,hasReference);
  const {data:quotaRaw,error:quotaError}=await db.rpc('consume_stockradar_api_quota',{p_user_id:user.id,p_bucket:'stock_ai'});if(quotaError||!quotaRaw)return json({status:'SERVICE_UNAVAILABLE',reason:'AI_QUOTA_RPC_FAILED'},503,origin);
  const quotaData=quotaRaw,remaining=Number.isFinite(Number(quotaData.remaining))?Number(quotaData.remaining):null,limit=Number.isFinite(Number(quotaData.limit))?Number(quotaData.limit):null,rate={...(limit!=null?{'X-RateLimit-Limit':String(limit)}:{}),...(remaining!=null?{'X-RateLimit-Remaining':String(remaining)}:{})};
  if(quotaData.allowed!==true){if(Number(quotaData.retry_after)>0)rate['Retry-After']=String(quotaData.retry_after);return json({status:'RATE_LIMITED',tier,answer:tier==='FREE'?'Bạn đã dùng đủ 10 lượt StockRadar AI hôm nay. Hạn mức được làm mới lúc 00:00 giờ Việt Nam.':'Hạn mức hiện tại đã dùng hết.',quota:{remaining:0,limit,reset_at:quotaData.reset_at||null}},429,origin,rate)}
  let fallback=deterministicStockRadarAnswer({mode,researchContext:scope==='ticker'?(contexts[0]||null):contexts,actionContext:[],question:message});fallback=appendPosition(fallback,scope,ticker,watch);
  const source={context_grades:{research_ready:contexts.filter(c=>c.context_grade==='RESEARCH_READY').length,reference_only:contexts.filter(c=>c.context_grade!=='RESEARCH_READY').length,requested:requestedTickers.length},snapshot_count:new Set(contexts.map(c=>c.snapshot_id).filter(Boolean)).size,generated_at:contexts.map(c=>String(c.generated_at||'')).filter(Boolean).sort().at(-1)||null,as_of_date:contexts.map(c=>String(c.as_of_date||'')).filter(Boolean).sort().at(-1)||null},quota={remaining,limit,unlimited:quotaData.unlimited===true,reset_at:quotaData.reset_at||null,reset_timezone:quotaData.daily_reset_timezone||null},base={scope,ticker:scope==='ticker'?ticker:null,horizon,tier,mode,source,quota,quota_consumed:true};
  if(mode==='METHOD_ONLY')return json({status:'READY',...base,answer_engine:'STOCKRADAR_DATA_ENGINE',answer:fallback},200,origin,rate);
  const key=Deno.env.get('OPENAI_API_KEY')?.trim();if(!key||Date.now()<providerDisabledUntil)return json({status:'READY_FALLBACK',reason:!key?'OPENAI_KEY_MISSING':'OPENAI_CIRCUIT_OPEN',...base,answer_engine:'STOCKRADAR_DATA_ENGINE',answer:fallback},200,origin,rate);
  const userContext={watchlist:watch,owned_count:watch.filter(x=>x.owns_stock).length};let response;try{response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:Deno.env.get('OPENAI_MODEL')?.trim()||'gpt-5-mini',instructions:STOCKRADAR_SYSTEM_CORE,input:JSON.stringify({RESPONSE_MODE:mode,ACCESS_TIER:tier,REQUEST_SCOPE:scope,REQUESTED_TICKER:ticker,REQUESTED_HORIZON:horizon,USER_QUESTION:message,USER_CONTEXT:userContext,RESEARCH_CONTEXT:scope==='ticker'?(contexts[0]||null):contexts}),max_output_tokens:1300,store:false})})}catch{return json({status:'READY_FALLBACK',reason:'OPENAI_NETWORK_ERROR',...base,answer_engine:'STOCKRADAR_DATA_ENGINE',answer:fallback},200,origin,rate)}
  let payload=null;try{payload=await response.json()}catch{}if(!response.ok){const code=String(payload?.error?.code||payload?.error?.type||'UNKNOWN').toUpperCase().replace(/[^A-Z0-9_]+/g,'_');if(response.status===429&&/CREDIT|QUOTA|BALANCE/.test(code))providerDisabledUntil=Date.now()+15*60*1000;return json({status:'READY_FALLBACK',reason:`OPENAI_${response.status}_${code}`,...base,answer_engine:'STOCKRADAR_DATA_ENGINE',answer:fallback},200,origin,rate)}
  return json({status:'READY',...base,answer_engine:'MODEL_PLUS_STOCKRADAR_DATA',answer:openAIText(payload)||fallback},200,origin,rate);
});
